---
title: "Visualization of Paddy Production, and Salinity Levels in Lower Mekong Delta, Vietnam"
author:
name: Huong Nguyen  
affiliation: AAED Department, Virginia Tech

output: pdf_document
classoption: landscape
geometry: margin=0.5in
---

```{r setup, include = FALSE}
#Include your packages here
library(rmarkdown)
options(tinytex.verbose = TRUE)
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
library(tidyverse)
library(readxl)
library(openxlsx)
library(fpp2)
library(tseries)
library(lubridate)
library(tidyverse)
#library(hrbrthemes)
library(rgdal)
library(sf)
library(viridisLite)
library(viridis)
library(Metrics)
library(MLmetrics)
library(kableExtra)
library(scales)
library(maps) # For map data
library(biscale)
library(sf)
library(cowplot)
library(usmap)
library(maps)
library(janitor)
library(purrr)
theme_set(theme_classic() + theme(legend.position="bottom") )
knitr::opts_chunk$set(echo = TRUE, 
                      message = FALSE,
                      warning = FALSE, 
                      fig.width = 7.5,
                      fig.align="center",
                      fig.margin=unit(c(0,0,0,0), 'cm'),
                      global.par = TRUE) 
knitr::opts_chunk$set(number_sections = FALSE)
```

```{r, include=F}
shape_rgdal <- readOGR('~/Downloads/stanford-bq365ww4197-shapefile',layer="bq365ww4197")

shape_sf <- read_sf('~/Downloads/stanford-bq365ww4197-shapefile',layer="bq365ww4197")

district_rgdal <- fortify(shape_rgdal)
district_sf <- fortify(shape_sf)

district_sf$id <- seq.int(nrow(district_sf)) - 1 
district_sf <- district_sf %>%
  mutate(id = as.character(id)) %>%
  select(id, adm_code, laa, nam, pop) 

district_MD <- district_sf %>%
  filter(nam == "An Giang" | nam == "Bac Lieu" | nam == "Ben Tre" |
           nam == "Ca Mau" | nam == "Can Tho" | nam == "Dong Thap" | 
           nam == "Hau Giang" | nam == "Kien Giang" | nam == "Soc Trang" | 
           nam == "Tien Giang" | nam == "Tra Vinh" | nam == "Long An" |
           nam == "Vinh Long") %>%
  select(id, adm_code, laa, nam, pop) 

MKD <- district_rgdal %>%
  right_join(district_sf, by = "id") %>%
  filter(nam == "An Giang" | nam == "Bac Lieu" | nam == "Ben Tre" |
           nam == "Ca Mau" | nam == "Can Tho" | nam == "Dong Thap" | 
           nam == "Hau Giang" | nam == "Kien Giang" | nam == "Soc Trang" | 
           nam == "Tien Giang" | nam == "Tra Vinh" | nam == "Long An" |
           nam == "Vinh Long") %>%
  filter(pop > 0)

MKD <- MKD %>%
  mutate(Subfix = case_when(
    laa == "Bac Lieu" ~ "City", 
    laa == "Ben Tre" ~ "City",
    laa == "Ca Mau" ~ "City",
    laa == "My Tho" ~ "City",
    laa == "Rach Gia" ~ "City",
    laa == "Sa Dec" ~ "City",
    laa == "Soc Trang" ~ "City",
    laa == "Tan An" ~ "City",
    laa == "Vi Thanh" ~ "City",
    laa == "Vinh Long" ~ "City",
    laa == "Long Xuyen" ~ "City",
    laa == "Tra Vinh" ~ "City",
    laa == "Chau Doc" ~ "City",
    laa == "Ha Tien" ~ "City",
    laa == "TP Cao Lanh" ~ "City",
    laa == "Phu Quoc" ~ "City",
    laa == "Gia Rai" ~ "Town",
    laa == "Go Cong" ~ "Town",
    laa == "Tan Chau" ~ "Town",
    laa == "Vinh Chau" ~ "Town",
    TRUE ~ "District")) %>%
  mutate(District_clean = case_when(
    laa == "TP Cao Lanh" & nam == "Dong Thap" ~ "Cao Lanh",
    laa == "TP Hong Ngu" & nam == "Dong Thap" ~ "Hong Ngu",
    laa == "TP. Hong Ngu" & nam == "Dong Thap" ~ "Hong Ngu",
    laa == "Mo Cay Bac" & nam == "Ben Tre" ~ "Mo Cay",
    laa == "Mo Cay Nam" & nam == "Ben Tre" ~ "Mo Cay",
    laa == "Ngoc Hien" & nam == "Ca Mau" ~ "Nam Can",
    laa == "Hoa Binh" & nam == "Bac Lieu" ~ "Vinh Loi",
    laa == "Giang Thanh" & nam == "Kien Giang" ~ "Kien Luong",
    laa == "Thoi Lai" & nam == "Can Tho" ~ "Co Do",
    laa == "Nga Bay" & nam == "Hau Giang" ~ "Phung Hiep",
    laa == "U Minh Thuong" & nam == "Kien Giang" ~ "Vinh Thuan",
    laa == "Giang Thanh" & nam == "Kien Giang" ~ "Kien Luong",
    laa == "Kien Tuong" & nam == "Long An" ~ "Moc Hoa",
    laa == "Chau Thanh" & nam == "Soc Trang" ~ "My Tu",
    laa == "Tran De" & nam == "Soc Trang" ~ "Long Phu",
    laa == "My Xuyen" & nam == "Soc Trang" ~ "Long Phu",
    laa == "Nga Nam" & nam == "Soc Trang" ~ "Thanh Tri",
    laa == "Binh Tan" & nam == "Vinh Long" ~ "Binh Minh",
    laa == "Go Cong Dong" & nam == "Tien Giang" ~ "Go Cong",
    laa == "Go Cong Tay" & nam == "Tien Giang" ~ "Go Cong",
    laa == "Tan Phu Dong" & nam == "Tien Giang" ~ "Go Cong",
    TRUE ~ laa)) %>%
  unite(District_clean, Subfix, col = DIST, sep = " ") %>%
  unite(DIST, nam, col = DIST, sep = ", ") 

MKD_id <- MKD %>%
  distinct(adm_code, DIST)

Data_Full <- read_excel("20230531_Processed_Data_Full.xlsx")
data_full_wgps <- Data_Full %>%
  full_join(MKD, by = "DIST") %>%
  filter(YEAR != 2021)

data_full_wgps <- data_full_wgps %>%
  mutate(Salinity_in_Feb = case_when(
    SALT_FEB <= 3 ~ 1,
    SALT_FEB <= 4 ~ 2,
    SALT_FEB > 4 ~ 3))
    
labs_plot <- c("<= 3 g/lt.", "3-4 g/lt.", ">4 g/lt.")

#br2 <- c(0, 3, 5, 7, 9)
data_full_wgps <- data_full_wgps %>%
#  group_by(YEAR, DIST) %>%
#  mutate(long = mean(long, na.rm = T), lat = mean(lat, na.rm = T)) %>%
#  ungroup() %>%
#  distinct(DIST, YEAR, long, lat, group, Y_PDX, SALT_FEB, Salinity_in_Feb) %>%
  mutate(Y_PDX_range = case_when(
    Y_PDX <= 5.5  ~ 1,
    Y_PDX <= 7  ~ 2,
    Y_PDX > 7  ~ 3
  ))

labs_plot_yield <- c("0-5.5 t/ha", "5.5-7 t/ha", "> 7 t/ha")
```

```{r spatialmap, out.width = '150%', fig.align = "center", fig.cap= "The spatial distribution of salinity level in February in MKD for the period 2000-2020", echo = F} 
data_full_wgps %>%
  filter(laa != "Phu Quoc" & pop > 0) %>%
  ggplot(aes(x = long, y = lat, group = group, fill = as.factor(Salinity_in_Feb))) +
  geom_polygon(col = "grey20") +
  coord_map("polyconic") +
  theme_void() + 
  facet_wrap(~YEAR, ncol = 6)  +
  scale_fill_brewer(palette = "Blues", na.value = NA, label = labs_plot) +
  labs(fill = "Salinty in Feb") +
  theme(legend.position = "bottom")
```

```{r spatialmap2, fig.align = "center", fig.cap= "The spatial distribution of Dong Xuan Paddy yield in MKD for the period 2000-2020", echo = F} 
data_full_wgps %>%
  filter(laa != "Phu Quoc" & pop > 0) %>%
  ggplot(aes(x = long, y = lat, group = group, fill = as.factor(Y_PDX_range))) +
  geom_polygon(col = "grey20") +
  coord_map("polyconic") +
  theme_void() + 
  facet_wrap(~YEAR, ncol = 6)  +
  scale_fill_brewer(palette = "DkGreens", na.value = NA, label = labs_plot_yield) +
  labs(fill = "Dong Xuan Season Yield") +
  theme(legend.position = "bottom")
```

```{r spatialmap3, out.width = '200%', fig.align = "center", fig.cap= "The correlation between paddy spring yield and salinity level in February in MKD for the period 2000-2020", echo = F}
data_full <- Data_Full %>%
  full_join(MKD_id, by = "DIST") %>%
  filter(YEAR != 2021)

data_full <- data_full %>%
  filter(!is.na(Y_PDX)) %>%
  mutate(Salinity_in_Feb = case_when(
    SALT_FEB <= 3 ~ 1,
    SALT_FEB <= 4 ~ 2,
    SALT_FEB > 4 ~ 3),
    Y_PDX_range = case_when(
    Y_PDX <= 5.5  ~ 1,
    Y_PDX <= 7  ~ 2,
    Y_PDX > 7  ~ 3
  )
  ) 

data_biscale <- bi_class(data_full, x = Salinity_in_Feb, y = Y_PDX_range, style = "equal", dim = 3) 

mkddata <- right_join(district_sf, data_biscale, by = c("adm_code")) %>%
  filter(laa != "Phu Quoc" & pop >0)

mkd_id <- Data_Full %>%
  full_join(MKD_id, by = "DIST") %>%
  distinct(adm_code, DIST) 

mkd <- district_sf %>%
  filter(adm_code %in% mkd_id$adm_code) %>%
  filter(laa != "Phu Quoc" & pop >0)

i<- 7 

mkd_map <- function(y) {
  mkddata %>%
  filter(YEAR == as.numeric(y)) %>%
  ggplot() +
  geom_sf(mapping = aes(fill = bi_class), color = "black", size = 0.2, show.legend = F) +
  geom_sf(data=mkd, fill = "transparent", color = "black", size = 0.2, show.legend = F) +
  bi_scale_fill(pal = "BlueYl", dim = 3) +
  bi_theme(base_size = i) + 
  ggtitle(y) + 
  theme(plot.margin=unit(c(0,0,0,0), 'cm'))
}

mkd_2000 <- mkd_map(2000)
mkd_2001 <- mkd_map(2001)
mkd_2002 <- mkd_map(2002)
mkd_2003 <- mkd_map(2003)
mkd_2004 <- mkd_map(2004)
mkd_2005 <- mkd_map(2005)
mkd_2006 <- mkd_map(2006)
mkd_2007 <- mkd_map(2007)
mkd_2008 <- mkd_map(2008)
mkd_2009 <- mkd_map(2009)
mkd_2010 <- mkd_map(2010)
mkd_2011 <- mkd_map(2011)
mkd_2012 <- mkd_map(2012)
mkd_2013 <- mkd_map(2013)
mkd_2014 <- mkd_map(2014)
mkd_2015 <- mkd_map(2015)
mkd_2016 <- mkd_map(2016)
mkd_2017 <- mkd_map(2017)
mkd_2018 <- mkd_map(2018)
mkd_2019 <- mkd_map(2019)
mkd_2020 <- mkd_map(2020)

legend <- bi_legend(pal = "BlueYl",
                    dim = 3,
                    xlab = "      Salinity Levles",
                    ylab = "  Yield",
                    size = 8,
                    pad_width = .2,
                    pad_color = "black") + 
  bi_theme(bg_color = "transparent",
           base_size = 8)

ggdraw() +
  draw_plot(cowplot::plot_grid(mkd_2000, mkd_2001, mkd_2002, mkd_2003, mkd_2004, 
                               mkd_2005, mkd_2006, mkd_2007, mkd_2008, mkd_2009,
                               mkd_2010, mkd_2011, mkd_2012, mkd_2013, mkd_2014,
                               mkd_2015, mkd_2016, mkd_2017, mkd_2018, mkd_2019,
                               mkd_2020, ncol=6)) +
  draw_plot(legend, 0.8, 0.01, 0.2, 0.2) +
  theme(plot.margin=unit(c(0,0,0,0), 'cm'))
```


```{r spatialmap4, out.width = '200%', fig.align = "center", fig.cap= "The correlation between change in paddy spring yield and salinity level in February in MKD for the period 2000-2020", echo = F}
data_full <- Data_Full %>%
  full_join(MKD_id, by = "DIST") %>%
  filter(YEAR != 2021) %>%
  group_by(adm_code) %>%
  mutate(change_SALT_FEB = SALT_FEB - lag(SALT_FEB,1),
         change_Y_PDX = Y_PDX - lag(Y_PDX, 1)) %>%
  ungroup() 

data_full <- data_full %>%
  filter(!is.na(change_Y_PDX)) %>%
  mutate(change_in_salinity_in_Feb = case_when(
    change_SALT_FEB < 0 ~ 1,
    change_SALT_FEB == 0 ~ 2,
    change_SALT_FEB > 0 ~ 3),
    change_in_Y_PDX = case_when(
    change_Y_PDX < 0  ~ 1, 
    change_Y_PDX == 0  ~ 2,
    change_Y_PDX > 0  ~ 3)
  ) 

data_biscale <- bi_class(data_full, x = change_in_salinity_in_Feb, y = change_in_Y_PDX, style = "equal", dim = 3) 

mkddata <- right_join(district_sf, data_biscale, by = c("adm_code")) %>%
  filter(laa != "Phu Quoc" & pop >0)

i<- 7 

mkd_map <- function(y) {
  mkddata %>%
  filter(YEAR == as.numeric(y)) %>%
  ggplot() +
  geom_sf(mapping = aes(fill = bi_class), color = "black", size = 0.2, show.legend = F) +
  geom_sf(data=mkd, fill = "transparent", color = "black", size = 0.2, show.legend = F) +
  bi_scale_fill(pal = "BlueYl", na.value = NA, dim = 3) +
  bi_theme(bg_color = "transparent", base_size = i) + 
  ggtitle(y) + 
  theme(plot.margin=unit(c(0,0,0,0), 'cm'))
}

#mkd_2000 <- mkd_map(2000)
mkd_2001 <- mkd_map(2001)
mkd_2002 <- mkd_map(2002)
mkd_2003 <- mkd_map(2003)
mkd_2004 <- mkd_map(2004)
mkd_2005 <- mkd_map(2005)
mkd_2006 <- mkd_map(2006)
mkd_2007 <- mkd_map(2007)
mkd_2008 <- mkd_map(2008)
mkd_2009 <- mkd_map(2009)
mkd_2010 <- mkd_map(2010)
mkd_2011 <- mkd_map(2011)
mkd_2012 <- mkd_map(2012)
mkd_2013 <- mkd_map(2013)
mkd_2014 <- mkd_map(2014)
mkd_2015 <- mkd_map(2015)
mkd_2016 <- mkd_map(2016)
mkd_2017 <- mkd_map(2017)
mkd_2018 <- mkd_map(2018)
mkd_2019 <- mkd_map(2019)
mkd_2020 <- mkd_map(2020)


legend <- bi_legend(pal = "BlueYl",
                    dim = 3,
                    xlab = "      Salinity Levles",
                    ylab = "  Yield",
                    size = 8,
                    pad_width = .2,
                    pad_color = "black") + 
  bi_theme(bg_color = "transparent",
           base_size = 8)

ggdraw() +
  draw_plot(cowplot::plot_grid(mkd_2001, mkd_2002, mkd_2003, mkd_2004, 
                               mkd_2005, mkd_2006, mkd_2007, mkd_2008, mkd_2009,
                               mkd_2010, mkd_2011, mkd_2012, mkd_2013, mkd_2014,
                               mkd_2015, mkd_2016, mkd_2017, mkd_2018, mkd_2019,
                               mkd_2020, ncol=6), 0, 0, 1, 1) +
  draw_plot(legend, 0.8, 0.01, 0.2, 0.2) +
  theme(plot.margin=unit(c(0,0,0,0), 'cm'))
```
